[build-system]
requires = ["setuptools>=64", "cython>=3.0", "numpy>=2.1.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pyafv"
version = "0.3.2"
description = "Python implementation of the active-finite-Voronoi (AFV) model"
readme = "README_PyPI.md"
authors = [
    { name = "Wei Wang (汪巍)", email = "ww000721@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE"] # Explicitly include the file
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "scipy>=1.15.3",
    "matplotlib>=3.10.7",
]

[project.urls]
"Download" = "https://pypi.org/project/pyafv/#files"
"Source Code" = "https://github.com/wwang721/pyafv"

[project.optional-dependencies]
examples = [
    "ipywidgets>=8.1.5",
    "jupyter>=1.1.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[tool.setuptools]
packages = ["pyafv"]  # optional but explicit
include-package-data = true

[tool.pytest.ini_options]
testpaths = ["tests"]
# pythonpath = ["."]  # not needed if package is installed
