[project]
name = "py-afv"
version = "0.2.4"
description = "Python code that implements the active-finite-Voronoi (AFV) model."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.2.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "scipy>=1.16.3",
    "setuptools>=80.9.0",
]

[project.optional-dependencies]
examples = [
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
# pythonpath = ["."]  # not needed with setuptools

[build-system]
requires = ["setuptools>=68", "wheel", "Cython>=3.0", "numpy"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["afv"]  # optional but explicit
