[project]
name = "py-afv"
version = "0.1.0"
description = "Python code that implements the active-finite-Voronoi (AFV) model."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "scipy>=1.16.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "tqdm>=4.67.1",
]

[tool.pytest.ini_options]
# pythonpath = ["."]  # not needed with setuptools
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# optional but explicit
packages = ["afv"]
