name: pytest

on:
  push:
    paths-ignore:
      - '**/README*'
      - 'examples/**'
      - 'assets/**'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/publish-to-pypi.yml'
      - '.github/workflows/zenodo-display.yml'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README*'
      - 'examples/**'
      - 'assets/**'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/publish-to-pypi.yml'
      - '.github/workflows/zenodo-display.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sync dependencies
        run: |
          uv sync --no-dev
          uv pip install "pytest>=8.3.4" "pytest-cov>=6.0.0"

      - name: Run tests
        run: |
          uv run --no-dev pytest --cov=pyafv --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
